# Generated by Django 5.2 on 2025-04-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
