# Generated by Django 5.2 on 2025-04-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_business_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
