# Generated by Django 5.2 on 2025-04-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_business_name_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='business',
            old_name='business_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='reviewlike',
            old_name='like_id',
            new_name='id',
        ),
    ]
