# Generated by Django 5.2 on 2025-05-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_business_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='business_id',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewlike',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviewlike',
            old_name='user_id',
            new_name='user',
        ),
    ]
