# Generated by Django 5.2 on 2025-05-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_owner_id_business_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
